import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import {
  Box,
  Heading,
  HStack,
  Text,
  useColorModeValue,
  VStack,
} from "@chakra-ui/react";
import Notes from "../components/Note";
import BaseLayout from "../components/layouts/BaseLayout";
import { auth, db } from "../lib/firebase";
import SignIn from "../components/SignIn";
import AuthCheck from "../components/AuthCheck";

const Home = ({ data }: { data: any[] }) => {
  return (
    <div>
      <Head>
        <title>Turbonote - LogIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthCheck>
        <SignIn />
      </AuthCheck>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const user = auth.currentUser;

  return {
    props: {
      data: null,
    },
    redirect: !user && "/signIn",
  };
};
